driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-10.04
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080}]
      - ["forwarded_port", {guest: 443, host: 8443}]
    run_list:
      - recipe[apt]
  - name: centos-6.5
  - name: centos-5.10

suites:
  - name: default
    run_list:
      - recipe[wordpress]
    attributes:
      mysql:
        server_root_password: "Please-Dont-Use-In-Production"
        server_debian_password: "Please-Dont-Use-In-Production"
        server_repl_password: "Please-Dont-Use-In-Production"
      wordpress:
        use_ssl: true
        ssl:
          country: "US"
          state: "Texas"
          city: "Houston"
          organization: "Foo Inc."
          email: "foo@example.com"
  - name: nginx
    run_list:
      - recipe[wordpress::nginx]
    attributes:
      mysql:
        server_root_password: "Please-Dont-Use-In-Production"
        server_debian_password: "Please-Dont-Use-In-Production"
        server_repl_password: "Please-Dont-Use-In-Production"
